GirlsOfSteelRobotics/GirlsOfSteelFRC

- settings.gradle
- y2021/OutreachBot/build.gradle
- y2022/CallistoRewrite/WPILib-License.md
- y2022/CallistoRewrite/build.gradle
- y2022/CallistoRewrite/src/main/deploy/example.txt
- y2022/CallistoRewrite/src/main/java/com/gos/calisto/v2/Constants.java
- y2022/CallistoRewrite/src/main/java/com/gos/calisto/v2/Main.java
- y2022/CallistoRewrite/src/main/java/com/gos/calisto/v2/Robot.java
- y2022/CallistoRewrite/src/main/java/com/gos/calisto/v2/RobotContainer.java
- y2022/CallistoRewrite/src/main/java/com/gos/calisto/v2/commands/ExampleCommand.java
- y2022/CallistoRewrite/src/main/java/com/gos/calisto/v2/subsystems/ExampleSubsystem.java
- y2022/CallistoRewrite/vendordeps/REVRobotics.json
- y2022/CallistoRewrite/vendordeps/SnobotSim.json
- y2022/CallistoRewrite/vendordeps/WPILibNewCommands.json
> added callisto project

- .idea/runConfigurations/2022_ChassisProject___Build.xml
- .idea/runConfigurations/2022_ChassisProject___Deploy.xml
- settings.gradle
Please accept! The robot doesn't actually exist, so of course it doesn't work :))))))
> Updated project file for ChassisProject

- y2022/RapidReact/simgui-ds.json
- y2022/RapidReact/simgui.json
- y2022/RapidReact/src/main/java/com/gos/rapidreact/Constants.java
- y2022/RapidReact/src/main/java/com/gos/rapidreact/RobotContainer.java
- y2022/RapidReact/src/main/java/com/gos/rapidreact/commands/CollectorDownCommand.java
- y2022/RapidReact/src/main/java/com/gos/rapidreact/commands/CollectorUpCommand.java
- y2022/RapidReact/src/main/java/com/gos/rapidreact/commands/RollerInCommand.java
- y2022/RapidReact/src/main/java/com/gos/rapidreact/commands/RollerOutCommand.java
- y2022/RapidReact/src/main/java/com/gos/rapidreact/commands/TeleopArcadeChassisCommand.java
- y2022/RapidReact/src/main/java/com/gos/rapidreact/subsystems/CollectorSubsystem.java
> created collector subsystem and commands

- .github/workflows/bazel.yml
- .gitignore
- build_scripts/bazel/deps/download_external_archives.bzl
- build_scripts/bazel/java_rules.bzl
- libraries/scripts/updater/replace_old_names.py
Apparently `GerritCodeReview/bazlets` move their release branches instead of cutting minor releases. This caused a SHA256 failure, making all the bazel build fail.
I also turned of mac since it was flakey, and updated other bazel dependencies
> [bazel] Fixing bazel builds

- settings.gradle
- y2022/RapidReactDashboard/build.gradle
- y2022/RapidReactDashboard/dashboard.yml
- y2022/RapidReactDashboard/src/dashboard_gen/java/com/gos/rapidreact/shuffleboard/RapidReactRobot.java
- y2022/RapidReactDashboard/src/dashboard_gen/java/com/gos/rapidreact/shuffleboard/super_structure/SuperStructureData.java
- y2022/RapidReactDashboard/src/dashboard_gen/java/com/gos/rapidreact/shuffleboard/super_structure/SuperStructureDataType.java
- y2022/RapidReactDashboard/src/dashboard_gen/java/com/gos/rapidreact/shuffleboard/super_structure/SuperStructureWidget.java
- y2022/RapidReactDashboard/src/main/java/com/gos/rapidreact/shuffleboard/Utils.java
- y2022/RapidReactDashboard/src/main/java/com/gos/rapidreact/shuffleboard/super_structure/SmartDashboardNames.java
- y2022/RapidReactDashboard/src/main/java/com/gos/rapidreact/shuffleboard/super_structure/SuperStructureController.java
- y2022/RapidReactDashboard/src/main/java/com/gos/rapidreact/shuffleboard/super_structure/SuperStructureStandaloneMain.java
- y2022/RapidReactDashboard/src/main/resources/com/gos/rapidreact/shuffleboard/super_structure/super_structure.fxml
- y2022/RapidReactDashboard/src/main/resources/com/gos/rapidreact/shuffleboard/super_structure/super_structure_widget.fxml
Created front end of super structure:
robot visually has chassis, horizontal conveyor, vertical conveyor, intake and intake wheel, hangar, and shooter
h convey, v convey, intake wheel, hangar, shooter motor speeds change color
hangar moves up/down
intake and intake wheel rotates
> Super structure

- y2022/RapidReact/src/main/java/com/gos/rapidreact/subsystems/ChassisSubsystem.java
- y2022/RapidReact/src/main/java/com/gos/rapidreact/subsystems/CollectorSubsystem.java
- y2022/RapidReact/src/main/java/com/gos/rapidreact/subsystems/HangerSubsystem.java
> Gear ratios

- y2022/RapidReact/characterization/config.json
- y2022/RapidReact/src/main/java/com/gos/rapidreact/auto_modes/TwoBallAutoCommandGroup.java
Created two new items to save the changes made on the team laptop:
- Characterization/config.json from the System Identification
- TwoBallAutoCommandGroup
> Characterization config & 2ballauto

- .github/workflows/gradle.yml
- libraries/scripts/updater/replace_gradlerio_files.py
- libraries/scripts/updater/update_everything.py
- settings.gradle
- y2022/RapidReact/simgui-ds.json
- y2022/RapidReact/src/main/java/com/gos/rapidreact/RobotContainer.java
Turns off a couple more old projects, codelabs. Basically everything except the current robot and dashboard, and their dependencies.
Also fixed some bugs found during simulation.
> Deprecate old projects

- y2022/RapidReact/src/main/java/com/gos/rapidreact/RobotContainer.java
- y2022/RapidReact/src/main/java/com/gos/rapidreact/commands/TeleopArcadeChassisCommand.java
- y2022/RapidReact/src/main/java/com/gos/rapidreact/subsystems/ChassisSubsystem.java
- y2022/RapidReact/src/main/java/com/gos/rapidreact/subsystems/CollectorSubsystem.java
- y2022/RapidReact/src/main/java/com/gos/rapidreact/subsystems/HangerSubsystem.java
- y2022/RapidReact/src/main/java/com/gos/rapidreact/subsystems/LEDManagerSubsystem.java
Requests from Wednesdays drive practice.
@ashley-wei for credit
> Drive practice 3/9

- build_scripts/bazel/deps/activate_dependencies.bzl
- y2020/2020InfiniteRecharge/src/main/java/com/gos/infinite_recharge/subsystems/ControlPanel.java
- y2020/2020InfiniteRecharge/src/main/java/com/gos/infinite_recharge/subsystems/Shooter.java
- y2020/2020InfiniteRecharge/src/main/java/com/gos/infinite_recharge/subsystems/ShooterConveyor.java
- y2020/2020InfiniteRecharge/src/main/java/com/gos/infinite_recharge/subsystems/Winch.java
Had to do some factory resets to fix some sparks booting into a follower mode for some reason.
Also fixed bazel builds
> Fixup 2020 robot, for defensive driver practice

- y2022/RapidReact/simgui.json
- y2022/RapidReact/src/main/java/com/gos/rapidreact/led/LEDAngleToTargetOverAndUnder.java
- y2022/RapidReact/src/main/java/com/gos/rapidreact/led/LEDAngleToTargetOverOrUnder.java
- y2022/RapidReact/src/main/java/com/gos/rapidreact/led/LEDColorLookup.java
- y2022/RapidReact/src/main/java/com/gos/rapidreact/led/LEDDistanceToTarget.java
- y2022/RapidReact/src/main/java/com/gos/rapidreact/led/LEDFlash.java
- y2022/RapidReact/src/main/java/com/gos/rapidreact/led/LEDRainbow.java
- y2022/RapidReact/src/main/java/com/gos/rapidreact/led/LEDSolidColor.java
- y2022/RapidReact/src/main/java/com/gos/rapidreact/led/mirrored/MirroredLEDBoolean.java
- y2022/RapidReact/src/main/java/com/gos/rapidreact/led/mirrored/MirroredLEDColorLookup.java
- y2022/RapidReact/src/main/java/com/gos/rapidreact/led/mirrored/MirroredLEDDistanceToTarget.java
- y2022/RapidReact/src/main/java/com/gos/rapidreact/led/mirrored/MirroredLEDFlash.java
- y2022/RapidReact/src/main/java/com/gos/rapidreact/led/mirrored/MirroredLEDRainbow.java
- y2022/RapidReact/src/main/java/com/gos/rapidreact/subsystems/LEDManagerSubsystem.java
Useful when you daisy chain one strip going up on one side of the robot, followed by another strip going down on the other side. Simplifies the logic
> Adding mirrored patterns for LEDS

- y2022/RapidReact/src/main/java/com/gos/rapidreact/auto_modes/AutoModeFactory.java
- y2022/RapidReact/src/main/java/com/gos/rapidreact/auto_modes/OneBallAutoHighCommandGroup.java
- y2022/RapidReact/src/main/java/com/gos/rapidreact/auto_modes/TwoBallAutoHighCommandGroup.java
> made one and two ball autos shooting high

- y2022/RapidReact/src/main/java/com/gos/rapidreact/auto_modes/AutoModeFactory.java
- y2022/RapidReact/src/main/java/com/gos/rapidreact/auto_modes/FiveBallAutoLow.java
- y2022/RapidReact/src/main/java/com/gos/rapidreact/auto_modes/OneBallAutoLow.java
- y2022/RapidReact/src/main/java/com/gos/rapidreact/auto_modes/OneBallAutoLowNewCommandGroup.java
- y2022/RapidReact/src/main/java/com/gos/rapidreact/auto_modes/ThreeBallAutoLow.java
- y2022/RapidReact/src/main/java/com/gos/rapidreact/auto_modes/TwoBallAutoLowNewCommandGroup.java
> renamed low autos to fit naming conventions

- .github/workflows/gradle.yml
- .gitignore
- .idea/checkstyle-idea.xml
- build_scripts/gradle/publish_java.gradle
- gos_vendordep_template.json
- libraries/GirlsOfSteelLib/build.gradle
- libraries/GirlsOfSteelLibCtre/build.gradle
- libraries/GirlsOfSteelLibRev/build.gradle
- settings.gradle
Allows teams to pull in our libraries as a vendor dep
> Add ability to publish our libraries to maven

- libraries/SwerveShuffleboard/build.gradle
- libraries/SwerveShuffleboard/dashboard.yml
- libraries/SwerveShuffleboard/src/dashboard_gen/java/com/gos/lib/shuffleboard/SwerveDrive.java
- libraries/SwerveShuffleboard/src/dashboard_gen/java/com/gos/lib/shuffleboard/swerve/SwerveDriveData.java
- libraries/SwerveShuffleboard/src/dashboard_gen/java/com/gos/lib/shuffleboard/swerve/SwerveDriveDataType.java
- libraries/SwerveShuffleboard/src/dashboard_gen/java/com/gos/lib/shuffleboard/swerve/SwerveDriveWidget.java
- libraries/SwerveShuffleboard/src/dashboard_gen/java/com/gos/lib/shuffleboard/swerve/SwerveModuleData.java
- libraries/SwerveShuffleboard/src/main/java/com/gos/lib/shuffleboard/Utils.java
- libraries/SwerveShuffleboard/src/main/java/com/gos/lib/shuffleboard/swerve/SmartDashboardNames.java
- libraries/SwerveShuffleboard/src/main/java/com/gos/lib/shuffleboard/swerve/SwerveDriveController.java
- libraries/SwerveShuffleboard/src/main/java/com/gos/lib/shuffleboard/swerve/SwerveDriveStandaloneMain.java
- libraries/SwerveShuffleboard/src/main/resources/com/gos/lib/shuffleboard/swerve/swerve_drive.fxml
- libraries/SwerveShuffleboard/src/main/resources/com/gos/lib/shuffleboard/swerve/swerve_drive_widget.fxml
- settings.gradle
Used this to help titanium titans get their java port up and running. They asked to see the code, and we may want it in the future for ourselves.
> Add shuffleboard plugin for swerve module visualization

- y2023/ChargedUp/src/main/deploy/pathplanner/DockandEngage_Community.path
- y2023/ChargedUp/src/main/deploy/pathplanner/OnePiece_DockAndEngage.path
- y2023/ChargedUp/src/main/java/com/gos/chargedup/autonomous/AutonomousFactory.java
Added OnePiece_DockAndEngage and DockandEngage_Community
> Add two paths

- 3rdParty_sb_widget_helper.gradle
- build.gradle
- libraries/GirlsOfSteelLib/src/main/java/com/gos/lib/checklists/BUILD.bazel
- libraries/GirlsOfSteelLibRev/src/main/java/com/gos/lib/rev/checklists/BUILD.bazel
- y2023/ChargedUp/ChargedUpDash.html
- y2023/ChargedUp/src/main/java/com/gos/chargedup/subsystems/ArmSubsystem.java
- y2023/ChargedUp/src/main/java/com/gos/chargedup/subsystems/ChassisSubsystem.java
- y2023/ChargedUp/src/main/java/com/gos/chargedup/subsystems/TurretSubsystem.java
- Added ability to automatically download Mechanical Advantages alerts widget
- Added bazel building for some new libraries
- Added FRC Web Components dashboard (this necessitated adding some names to the test commands)
> Mono repo cleanup

- libraries/GirlsOfSteelLib/src/main/java/com/gos/lib/properties/WpiProfiledPidPropertyBuilder.java
> Fix bug in profiled PID controller

- libraries/GirlsOfSteelLib/src/main/java/com/gos/lib/checklists/PneumaticHubAlerts.java
- libraries/GirlsOfSteelLib/src/main/java/com/gos/lib/checklists/PowerDistributionAlerts.java
- libraries/GirlsOfSteelLibCtre/src/main/java/com/gos/lib/ctre/BUILD.bazel
- libraries/GirlsOfSteelLibCtre/src/main/java/com/gos/lib/ctre/PigeonAlerts.java
- libraries/GirlsOfSteelLibRev/src/main/java/com/gos/lib/rev/SparkMaxAlerts.java
- y2023/ChargedUp/build.gradle
- y2023/ChargedUp/src/main/java/com/gos/chargedup/subsystems/ChassisSubsystem.java
also incorporated with chassis
> Faults updating

- y2023/ChargedUp/ChargedUpDash.html
- y2023/ChargedUp/simgui.json
- y2023/ChargedUp/src/main/java/com/gos/chargedup/GosField.java
- y2023/ChargedUp/src/main/java/com/gos/chargedup/RectangleInterface.java
- y2023/ChargedUp/src/main/java/com/gos/chargedup/subsystems/ChassisSubsystem.java
- y2023/ChargedUp/src/main/java/com/gos/chargedup/subsystems/PhotonVisionSubsystem.java
- y2023/ChargedUp/src/main/java/com/gos/chargedup/subsystems/TurretSubsystem.java
There were lots of places we were adding elements to the field gui. This creates a class to make certain concepts more reusable (multi-camera), and make it easier to do things like clear poses when a command is finished.
> Add custom field object to ease managment

- libraries/scripts/git/install_gitconfig.py
Adds commit hooks to check for 
- unstaged pathplanner files
- if you are on master
- if you are reusing a merged remote branch
Also automatically prunes deleted remote branches on fetch / pull
> Add more git config setup to avoid comitting to main

- y2024/Crescendo/networktables.json
- y2024/Crescendo/simgui.json
- y2024/Crescendo/src/main/java/com/gos/crescendo2024/RobotContainer.java
- y2024/Crescendo/src/main/java/com/gos/crescendo2024/subsystems/ShooterSubsystem.java
> Shooter Subsystem Open Loop

- y2024/Crescendo/simgui-ds.json
- y2024/Crescendo/simgui.json
- y2024/Crescendo/src/main/java/com/gos/crescendo2024/Constants.java
- y2024/Crescendo/src/main/java/com/gos/crescendo2024/RobotContainer.java
- y2024/Crescendo/src/main/java/com/gos/crescendo2024/commands/ArmPivotJoystickCommand.java
- y2024/Crescendo/src/main/java/com/gos/crescendo2024/subsystems/ArmPivotSubsystem.java
> Arm Pivot Subsystem Added 

- gos_vendordep_template.json
- y2024/Crescendo/src/main/java/com/gos/crescendo2024/RobotContainer.java
- y2024/Crescendo/src/main/java/com/gos/crescendo2024/commands/TeleopSwerveDrive.java
- y2024/Crescendo/src/main/java/com/gos/crescendo2024/subsystems/ChassisSubsystem.java
Also add the ability to reset the robots gyro, which is helpful when the swerve drive boots in the wrong orientation
> Fixup vendordep template

- .idea/.name
- libraries/GirlsOfSteelLibRev/src/main/java/com/gos/lib/rev/swerve/RevSwerveChassis.java
- y2024/Crescendo/dashboard.yml
- y2024/Crescendo/src/main/java/com/gos/crescendo2024/subsystems/ArmPivotSubsystem.java
- y2024/Crescendo/src/main/java/com/gos/crescendo2024/subsystems/ChassisSubsystem.java
- y2024/Crescendo/src/main/java/com/gos/crescendo2024/subsystems/IntakeSubsystem.java
- y2024/Crescendo/src/main/java/com/gos/crescendo2024/subsystems/PhotonVisionSubsystem.java
- y2024/Crescendo/vendordeps/PathplannerLib.json
- y2024/Crescendo/vendordeps/Phoenix6.json
- y2024/Crescendo/vendordeps/REVLib.json
- y2024/Crescendo/vendordeps/SnobotSim.json
Added Photon vision to subsystem
> Photon vision subsystem

- y2024/Crescendo/src/main/java/com/gos/crescendo2024/subsystems/ChassisSubsystem.java
> Update chassis gear ratio

- build_scripts/bazel/deps/setup_dependencies.bzl
- libraries/GirlsOfSteelLib/src/main/java/com/gos/lib/properties/feedforward/SimpleMotorFeedForwardProperty.java
- libraries/GirlsOfSteelLibRev/src/main/java/com/gos/lib/rev/swerve/RevSwerveChassis.java
- libraries/scripts/updater/replace_old_names.py
- libraries/scripts/updater/update_everything.py
- libraries/scripts/updater/update_vendor_deps.py
- libraries/scripts/updater/utils.py
- old_robots/y2023/ChargedUp/src/main/java/com/gos/chargedup/commands/SwerveChassisJoystickCommand.java
- old_robots/y2023/ChargedUp/src/main/java/com/gos/chargedup/subsystems/TankDriveChassisSubsystem.java
- y2024/Crescendo/simgui.json
- y2024/Crescendo/src/main/java/com/gos/crescendo2024/ChoreoUtils.java
> Add ability to run choreo from bazel

- y2024/Crescendo/simgui.json
- y2025/Reefscape/WebDash.html
- y2025/Reefscape/networktables.json
- y2025/Reefscape/simgui-ds.json
- y2025/Reefscape/simgui.json
- y2025/Reefscape/src/main/java/com/gos/reefscape/subsystems/REVchassisSubsystem.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/subsystems/RevSwerveModule.java
tuned swerve and drive motors :)
was very fun and educational
> tuned swerve and drive motors :)

- y2025/Reefscape/WebDash.html
- y2025/Reefscape/simgui-ds.json
- y2025/Reefscape/simgui.json
- y2025/Reefscape/src/main/java/com/gos/reefscape/Constants.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/RobotContainer.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/commands/MoveElevatorWithJoystickCommand.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/subsystems/ElevatorSubsystem.java
> elevator subsystem openloop stuff :)

- y2025/Reefscape/simgui.json
- y2025/Reefscape/src/main/java/com/gos/reefscape/Constants.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/RobotContainer.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/subsystems/AlgaeSubsystem.java
Made Intake In, Intake Out, and Intake Until
fixes #585
> Algae subsystem

- y2025/Reefscape/simgui-ds.json
- y2025/Reefscape/simgui.json
- y2025/Reefscape/src/main/java/com/gos/reefscape/Constants.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/RobotContainer.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/commands/MovePivotWithJoystickCommand.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/subsystems/PivotSubsystem.java
> added open loop pivot subsystem

- y2025/Reefscape/simgui.json
- y2025/Reefscape/src/main/java/com/gos/reefscape/Constants.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/RobotContainer.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/subsystems/ElevatorSubsystem.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/subsystems/SuperStructureViz.java
Ported from their C++ version.
https://github.com/frc2053/Robot2025/blob/dd302767522e812b0bbfe350672c9a416b680353/src/main/include/str/SuperstructureDisplay.h
> Steal Reef Mech2d from FRC2053

- y2025/Reefscape/WebDash.html
- y2025/Reefscape/networktables.json
- y2025/Reefscape/simgui-ds.json
- y2025/Reefscape/simgui.json
- y2025/Reefscape/src/main/java/com/gos/reefscape/RobotContainer.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/subsystems/ElevatorSubsystem.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/subsystems/SuperStructureViz.java
> Added elevator subsystem pid and elevator drawing.

- y2025/Reefscape/choreo_variables_to_java.py
- y2025/Reefscape/simgui.json
- y2025/Reefscape/src/main/java/com/gos/reefscape/ChoreoPoses.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/RobotContainer.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/auto/modes/TwoPieceCoral.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/auto/modes/center/Center_H_GH_EFCommandGroup.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/commands/Autos.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/commands/DavidDriveCommand.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/commands/SwerveWithJoystickCommand.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/subsystems/ChassisSubsystem.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/subsystems/TunerConstants.java
> Drive to pose

- y2025/Reefscape/networktables.json
- y2025/Reefscape/simgui.json
- y2025/Reefscape/src/main/java/com/gos/reefscape/GosField.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/RobotExtrinsic.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/subsystems/ChassisSubsystem.java
- y2025/Reefscape/src/main/java/org/littletonrobotics/frc2025/FieldConstants.java
> april tag copy and paste

- y2025/Reefscape/networktables.json
- y2025/Reefscape/simgui.json
- y2025/Reefscape/src/main/java/com/gos/reefscape/Constants.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/RobotContainer.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/led_patterns/DisabledPatterns.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/led_patterns/EnabledPatterns.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/subsystems/LEDSubsystem.java
> added led subsystem and patterns

- y2025/Reefscape/src/main/java/com/gos/reefscape/Constants.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/RobotContainer.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/commands/MoveElevatorWithJoystickCommand.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/subsystems/AlgaeSubsystem.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/subsystems/ChassisSubsystem.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/subsystems/CoralSubsystem.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/subsystems/ElevatorSubsystem.java
- y2025/Reefscape/src/main/java/com/gos/reefscape/subsystems/PivotSubsystem.java
so we did the elevator but we realized it was leader follower so we changed it so it did that so all of the motors were accounted for. also we did clear sticky faults for all
thank you,
sonia 🤩
> elevator add follow motor
